Complex search filters with a substring matching expression, followed by another search expression, generate an exception The order seems to be very important with this bug, because if the substring matching expression comes after say, a relational expression, it executes without error. The following two filters illustrate that point --
- ERROR READING -

    <filter>
      <and>
        <substrings name="sn">
          <any>Ku</any>
        </substrings>
        <equalityMatch name="objectClass">
          <value>person</value>
        </equalityMatch>
      </and>
    </filter>

-SUCCESSFUL  READ -

   <filter>
      <and>
        <equalityMatch name="objectClass">
          <value>person</value>
        </equalityMatch>
        <substrings name="sn">
          <any>Ku</any>
        </substrings>
      </and>
    </filter>

- STACK TRACE -

LDAPLocalException: The following error occured while parsing DSML: org.xml.sax.SAXException: invalid substrings tag: equal
ityMatch (84) Decoding Error
org.xml.sax.SAXException: invalid substrings tag: equalityMatch
        at com.novell.ldap.util.DSMLReader.<init>(Unknown Source)
        at com.novell.ldap.util.DSMLReader.<init>(Unknown Source)
        at Dsml2Ldap.main(Dsml2Ldap.java:78)